#!/bin/bash

set -e

#apt-get install software-properties-common
#apt-add-repository ppa:swi-prolog/stable
#apt-get update
#apt-get install swi-prolog

wget https://logtalk.org/files/logtalk_3.62.0-1_all.deb
sudo dpkg -i logtalk_3.62.0-1_all.deb
