#!/bin/bash

set -e

python3 -m logtalk_kernel.install

mkdir eclipse
cd eclipse
wget http://eclipseclp.org/Distribution/CurrentRelease/7.1_13%20x86_64_linux%20Intel-64bit-Linux/eclipse_basic.tgz
wget http://eclipseclp.org/Distribution/CurrentRelease/7.1_13%20x86_64_linux%20Intel-64bit-Linux/eclipse_doc.tgz
wget http://eclipseclp.org/Distribution/CurrentRelease/7.1_13%20x86_64_linux%20Intel-64bit-Linux/UNPACK
chmod a+x UNPACK
./UNPACK
echo -e "\n\n\n\n\n\n" | ./RUNME
echo 'export PATH=$PATH:$HOME/eclipse/bin/x86_64_linux' >> $HOME/.profile
cd ~

git clone --depth 1 https://github.com/didoudiaz/gprolog
cd gprolog/src
./configure --prefix=/in-place && make && make install
echo 'export PATH=$PATH:$HOME/gprolog/bin' >> $HOME/.profile
cd ~

git clone --depth 1 --branch V9.1.6 https://github.com/SWI-Prolog/swipl-devel.git
cd swipl-devel
git submodule update --init
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME -G Ninja ..
ninja
ninja install
echo 'export PATH=$PATH:$HOME/bin' >> $HOME/.profile
cd ~

git clone --depth 1 --branch v2.10.13 https://github.com/trealla-prolog/trealla
cd trealla
make clean && make NOSSL=1
echo 'export PATH=$PATH:$HOME/trealla' >> $HOME/.profile
cd ~

#git clone --depth 1 https://github.com/vscosta/yap
#cd yap
#mkdir build
#cd build
#cmake .. && make
#echo 'export PATH=$PATH:$HOME/yap/build' >> $HOME/.profile
#cd ~

git clone --depth 1 https://github.com/LogtalkDotOrg/logtalk3.git

echo 'export LOGTALKHOME=$HOME/logtalk3' >> $HOME/.profile
echo 'export LOGTALKUSER=$HOME/logtalk3' >> $HOME/.profile
echo 'export PATH=$PATH:$LOGTALKHOME/tools/diagrams' >> $HOME/.profile
echo 'export PATH=$PATH:$LOGTALKHOME/tools/lgtdoc/xml' >> $HOME/.profile
echo 'export PATH=$PATH:$LOGTALKHOME/scripts' >> $HOME/.profile
echo 'export PATH=$PATH:$LOGTALKHOME/integration' >> $HOME/.profile
echo 'export MANPATH=$MANPATH:$LOGTALKHOME/man' >> $HOME/.profile
