#!/bin/bash

set -e

python3 -m logtalk_kernel.install

#apt-get install software-properties-common
#apt-add-repository ppa:swi-prolog/stable
#apt-get update
#apt-get install swi-prolog

git clone --depth 1 https://github.com/trealla-prolog/trealla
cd trealla
make clean && make NOSSL=1
echo 'export PATH=$PATH:$HOME/trealla' >> $HOME/.profile
cd ~

git clone --depth 1 https://github.com/didoudiaz/gprolog
cd gprolog/src
./configure --prefix=/in-place && make && make install
echo 'export PATH=$PATH:$HOME/gprolog/bin' >> $HOME/.profile
cd ~

git clone --depth 1 https://github.com/LogtalkDotOrg/logtalk3.git

echo 'export LOGTALKHOME=$HOME/logtalk3' >> $HOME/.profile
echo 'export LOGTALKUSER=$HOME/logtalk3' >> $HOME/.profile
echo 'export PATH=$PATH:$LOGTALKHOME/tools/diagrams' >> $HOME/.profile
echo 'export PATH=$PATH:$LOGTALKHOME/tools/lgtdoc/xml' >> $HOME/.profile
echo 'export PATH=$PATH:$LOGTALKHOME/scripts' >> $HOME/.profile
echo 'export PATH=$PATH:$LOGTALKHOME/integration' >> $HOME/.profile
echo 'export MANPATH=$MANPATH:$LOGTALKHOME/man' >> $HOME/.profile
